[package]
name = "rusty_hangman"
version = "0.1.0"
authors = ["Christopher Wilke <christopher.wilke86@googlemail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"